//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsomeServicoCalculadora.CalculadoraSoap")]
    public interface CalculadoraSoap {
        
        // CODEGEN: Generating message contract since element name HelloResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Hello", ReplyAction="*")]
        ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloResponse Hello(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Hello", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloResponse> HelloAsync(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequest request);
        
        // CODEGEN: Generating message contract since element name ChamarResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Chamar", ReplyAction="*")]
        ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarResponse Chamar(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Chamar", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarResponse> ChamarAsync(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequest request);
        
        // CODEGEN: Generating message contract since element name Operacao from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealizaCalculo", ReplyAction="*")]
        ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoResponse RealizaCalculo(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RealizaCalculo", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoResponse> RealizaCalculoAsync(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Hello", Namespace="http://tempuri.org/", Order=0)]
        public ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequestBody Body;
        
        public HelloRequest() {
        }
        
        public HelloRequest(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloRequestBody {
        
        public HelloRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloResponseBody Body;
        
        public HelloResponse() {
        }
        
        public HelloResponse(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloResult;
        
        public HelloResponseBody() {
        }
        
        public HelloResponseBody(string HelloResult) {
            this.HelloResult = HelloResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChamarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Chamar", Namespace="http://tempuri.org/", Order=0)]
        public ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequestBody Body;
        
        public ChamarRequest() {
        }
        
        public ChamarRequest(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChamarRequestBody {
        
        public ChamarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChamarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChamarResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarResponseBody Body;
        
        public ChamarResponse() {
        }
        
        public ChamarResponse(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChamarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ChamarResult;
        
        public ChamarResponseBody() {
        }
        
        public ChamarResponseBody(string ChamarResult) {
            this.ChamarResult = ChamarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealizaCalculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RealizaCalculo", Namespace="http://tempuri.org/", Order=0)]
        public ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequestBody Body;
        
        public RealizaCalculoRequest() {
        }
        
        public RealizaCalculoRequest(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RealizaCalculoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Operacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ValorUm;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ValorDois;
        
        public RealizaCalculoRequestBody() {
        }
        
        public RealizaCalculoRequestBody(string Operacao, string ValorUm, string ValorDois) {
            this.Operacao = Operacao;
            this.ValorUm = ValorUm;
            this.ValorDois = ValorDois;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RealizaCalculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RealizaCalculoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoResponseBody Body;
        
        public RealizaCalculoResponse() {
        }
        
        public RealizaCalculoResponse(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RealizaCalculoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RealizaCalculoResult;
        
        public RealizaCalculoResponseBody() {
        }
        
        public RealizaCalculoResponseBody(string RealizaCalculoResult) {
            this.RealizaCalculoResult = RealizaCalculoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculadoraSoapChannel : ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraSoapClient : System.ServiceModel.ClientBase<ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap>, ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap {
        
        public CalculadoraSoapClient() {
        }
        
        public CalculadoraSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloResponse ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap.Hello(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequest request) {
            return base.Channel.Hello(request);
        }
        
        public string Hello() {
            ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequest inValue = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequest();
            inValue.Body = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequestBody();
            ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloResponse retVal = ((ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap)(this)).Hello(inValue);
            return retVal.Body.HelloResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloResponse> ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap.HelloAsync(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequest request) {
            return base.Channel.HelloAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloResponse> HelloAsync() {
            ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequest inValue = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequest();
            inValue.Body = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.HelloRequestBody();
            return ((ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap)(this)).HelloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarResponse ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap.Chamar(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequest request) {
            return base.Channel.Chamar(request);
        }
        
        public string Chamar() {
            ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequest inValue = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequest();
            inValue.Body = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequestBody();
            ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarResponse retVal = ((ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap)(this)).Chamar(inValue);
            return retVal.Body.ChamarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarResponse> ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap.ChamarAsync(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequest request) {
            return base.Channel.ChamarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarResponse> ChamarAsync() {
            ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequest inValue = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequest();
            inValue.Body = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.ChamarRequestBody();
            return ((ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap)(this)).ChamarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoResponse ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap.RealizaCalculo(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequest request) {
            return base.Channel.RealizaCalculo(request);
        }
        
        public string RealizaCalculo(string Operacao, string ValorUm, string ValorDois) {
            ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequest inValue = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequest();
            inValue.Body = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequestBody();
            inValue.Body.Operacao = Operacao;
            inValue.Body.ValorUm = ValorUm;
            inValue.Body.ValorDois = ValorDois;
            ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoResponse retVal = ((ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap)(this)).RealizaCalculo(inValue);
            return retVal.Body.RealizaCalculoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoResponse> ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap.RealizaCalculoAsync(ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequest request) {
            return base.Channel.RealizaCalculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoResponse> RealizaCalculoAsync(string Operacao, string ValorUm, string ValorDois) {
            ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequest inValue = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequest();
            inValue.Body = new ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.RealizaCalculoRequestBody();
            inValue.Body.Operacao = Operacao;
            inValue.Body.ValorUm = ValorUm;
            inValue.Body.ValorDois = ValorDois;
            return ((ConsumindoWebServiceCalculadora.ConsomeServicoCalculadora.CalculadoraSoap)(this)).RealizaCalculoAsync(inValue);
        }
    }
}
